app_site:
    resource: "@AppBundle/Controller/SiteController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_review:
    resource: "@AppBundle/Controller/ReviewController.php"
    type:     annotation

app_plane_model:
    resource: "@AppBundle/Controller/PlaneModelController.php"
    type:     annotation

app_reservation:
    resource: "@AppBundle/Controller/ReservationController.php"
    type:     annotation

app_flight:
    resource: "@AppBundle/Controller/FlightController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller"
    prefix:   /
    type: annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin