<?php

namespace Proxies\__CG__\WCS\CoavBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PlaneModel extends \WCS\CoavBundle\Entity\PlaneModel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'id', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'model', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'manufacturer', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'cruiseSpeed', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'nbSeats', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'status', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'models');
        }

        return array('__isInitialized__', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'id', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'model', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'manufacturer', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'cruiseSpeed', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'nbSeats', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'status', '' . "\0" . 'WCS\\CoavBundle\\Entity\\PlaneModel' . "\0" . 'models');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PlaneModel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel($model)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', array($model));

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', array());

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturer($manufacturer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturer', array($manufacturer));

        return parent::setManufacturer($manufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturer', array());

        return parent::getManufacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCruiseSpeed($cruiseSpeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCruiseSpeed', array($cruiseSpeed));

        return parent::setCruiseSpeed($cruiseSpeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCruiseSpeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCruiseSpeed', array());

        return parent::getCruiseSpeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSeats($nbSeats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSeats', array($nbSeats));

        return parent::setNbSeats($nbSeats);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSeats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSeats', array());

        return parent::getNbSeats();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addModel(\WCS\CoavBundle\Entity\Flight $models)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModel', array($models));

        return parent::addModel($models);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModel(\WCS\CoavBundle\Entity\Flight $models)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModel', array($models));

        return parent::removeModel($models);
    }

    /**
     * {@inheritDoc}
     */
    public function getModels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModels', array());

        return parent::getModels();
    }

}
